# Database
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/mock?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
spring.datasource.username=${DB_USERNAME:mock}
spring.datasource.password=${DB_PASSWORD:mock}

# Mock OAuth
mock.oauth.client-secret=${MOCK_OAUTH_CLIENT_SECRET:local-mock-client-secret}
